<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { detectPlatform, extractUrl, platformNames } from '../../services/platform';
import { ensureSession, getMe, resolveMaterial } from '../../services/api';
const input = ref(''); const isParsing = ref(false); const points = ref(0); const platform = computed(() => detectPlatform(input.value));
const canResolve = computed(() => Boolean(platform.value) && !isParsing.value);
function paste() { uni.getClipboardData({ success: ({ data }) => { input.value = data; }, fail: () => uni.showToast({ title: '请手动粘贴链接', icon: 'none' }) }); }
function onInput(event: Event) { const detail = (event as CustomEvent<{ value?: string }>).detail; input.value = detail?.value || (event.target as HTMLTextAreaElement | null)?.value || ''; }
async function resolve() { if (!canResolve.value) return; isParsing.value = true; try { const job = await resolveMaterial(input.value); points.value -= 1; uni.navigateTo({ url: `/pages/result/index?id=${job.id}&platform=${job.platform}` }); } catch (error) { const message = (error as { message?: string })?.message || '暂时没有解析成功，请检查链接或稍后重试'; if (message.includes('NO_POINTS')) { uni.showModal({ title: '点数不足', content: '可使用兑换码补充点数；当前为免费内测。', confirmText: '去兑换', success: ({ confirm }) => { if (confirm) goMe(); } }); } else uni.showToast({ title: message, icon: 'none' }); } finally { isParsing.value = false; } }
function goMe() { uni.switchTab({ url: '/pages/me/index' }); }
onMounted(async () => { try { await ensureSession(); points.value = (await getMe()).pointsBalance; } catch { uni.showToast({ title: '服务连接失败，请检查 API', icon: 'none' }); } });
</script>

<template>
  <view class="screen">
    <view class="orb orb-one" /><view class="orb orb-two" />
    <view class="hero"><view class="eyebrow">LINK · MEDIA · HELPER</view><text class="title">AI素材助手</text><text class="subtitle">链接提取高清原图 / 视频素材</text></view>
    <view class="platform-panel"><text class="section-label">支持平台</text><view class="platforms"><view v-for="item in [['豆','豆包'],['抖','抖音'],['红','小红书'],['微','视频号'],['即','即梦'],['快','快手']]" :key="item[1]" class="platform"><view class="mark">{{ item[0] }}</view><text>{{ item[1] }}</text></view></view><text class="platform-more">以及千问、B站、西瓜、微博等 30+ 平台</text></view>
    <view class="resolve-card"><view class="card-top"><text>粘贴分享链接</text><text class="paste" @click="paste">粘贴</text></view><textarea :value="input" :maxlength="4000" auto-height placeholder="粘贴视频号、豆包、即梦、抖音、快手、小红书等分享链接" @input="onInput" /><view class="hint"><text v-if="platform">已识别：{{ platformNames[platform] }}</text><text v-else-if="input">请输入完整分享链接</text><text v-else>自动识别，无需手动选择平台</text></view><button class="primary" :class="{ disabled: !canResolve }" :loading="isParsing" @click="resolve">{{ isParsing ? '正在解析素材…' : '一键提取素材' }}</button></view>
    <view class="quota"><view><text class="quota-number">{{ points }}</text><text> 我的点数</text></view><text class="redeem" @click="goMe">兑换码 ›</text></view>
    <view class="recent"><text class="section-label">最近提取</text><view class="empty"><text class="empty-icon">✦</text><text>还没有提取记录</text><text class="empty-sub">粘贴一条分享链接开始吧</text></view></view>
  </view>
</template>

<style scoped>
.screen{min-height:100vh;padding:calc(76rpx + var(--status-bar-height)) 36rpx 160rpx;box-sizing:border-box;position:relative;overflow:hidden}.orb{position:absolute;border-radius:50%;filter:blur(3px);opacity:.22}.orb-one{width:320rpx;height:320rpx;background:#a88cf8;right:-130rpx;top:-100rpx}.orb-two{width:220rpx;height:220rpx;background:#ffb8cc;left:-110rpx;top:350rpx}.hero,.platform-panel,.resolve-card,.quota,.recent{position:relative}.eyebrow,.section-label{font-size:21rpx;letter-spacing:2rpx;color:var(--muted);font-weight:700}.title{display:block;font-family:serif;font-size:68rpx;letter-spacing:2rpx;margin-top:16rpx}.subtitle{display:block;margin-top:14rpx;color:#696374;font-size:28rpx}.platform-panel{background:var(--surface);border:1rpx solid var(--line);border-radius:32rpx;margin-top:62rpx;padding:30rpx}.platforms{display:grid;grid-template-columns:repeat(6,1fr);gap:10rpx;margin-top:28rpx}.platform{font-size:19rpx;text-align:center;color:#4a4554}.mark{width:64rpx;height:64rpx;margin:0 auto 10rpx;display:grid;place-items:center;border-radius:20rpx;background:var(--violet-soft);color:var(--violet);font-size:25rpx;font-weight:800}.platform-more{display:block;margin-top:22rpx;text-align:center;font-size:21rpx;color:#928c9d}.resolve-card{margin-top:28rpx;background:var(--surface);border-radius:32rpx;padding:30rpx;box-shadow:0 18rpx 48rpx rgba(55,37,90,.08)}.card-top{display:flex;justify-content:space-between;font-size:28rpx;font-weight:700}.paste,.redeem{color:var(--violet)}textarea{width:100%;min-height:142rpx;margin-top:24rpx;font-size:27rpx;line-height:1.6;color:var(--ink)}.hint{font-size:22rpx;color:#928c9d;margin-top:16rpx;min-height:30rpx}.primary{margin-top:28rpx;border-radius:18rpx;background:var(--violet);color:#fff;font-size:30rpx;font-weight:700;height:96rpx;line-height:96rpx}.primary.disabled{opacity:.4}.quota{display:flex;justify-content:space-between;align-items:center;padding:32rpx 10rpx;font-size:25rpx}.quota-number{font-size:46rpx;font-weight:800;color:var(--violet)}.recent{margin-top:18rpx}.empty{margin-top:22rpx;border:2rpx dashed #dedbe8;border-radius:28rpx;padding:50rpx;display:flex;flex-direction:column;align-items:center;color:#7f798c;font-size:26rpx}.empty-icon{font-size:44rpx;color:#b09aff;margin-bottom:8rpx}.empty-sub{font-size:22rpx;margin-top:8rpx;color:#a9a4b1}
</style>
