<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
function acceptLoginHandoff() { const p = new URLSearchParams(location.search); const t = p.get('adminToken'); const profile = p.get('adminProfile'); if (!t) return; localStorage.setItem('admin-token', t); if (profile) localStorage.setItem('admin-profile', profile); p.delete('adminToken'); p.delete('adminProfile'); history.replaceState({}, document.title, location.pathname); }
acceptLoginHandoff();
type View = 'overview' | 'tenants' | 'providers' | 'calls' | 'audits';
const api = import.meta.env.VITE_API_BASE_URL || 'http://127.0.0.1:3000'; const token = localStorage.getItem('admin-token'); const profile = JSON.parse(localStorage.getItem('admin-profile') || '{}');
const view = ref<View>('overview'); const loading = ref(false); const error = ref(''); const overview = ref<any>(null); const tenants = ref<any[]>([]); const providers = ref<any[]>([]); const calls = ref<any[]>([]); const audits = ref<any[]>([]); const dialog = ref<'tenant' | 'quota' | 'activation' | null>(null); const form = ref<any>({});
const menu: [View, string, string][] = [['overview', '总览', '◈'], ['tenants', '租户', '◎'], ['providers', 'Provider', '⌁'], ['calls', 'Provider 调用', '↗'], ['audits', '审计日志', '▤']];
async function request(path: string, options: RequestInit = {}) { if (!token) { location.href = import.meta.env.VITE_ADMIN_PORTAL_URL || (location.hostname === 'localhost' ? 'http://localhost:5174/' : `${location.origin}/admin/`); throw new Error('登录已过期'); } const response = await fetch(`${api}/api/super-admin/${path}`, { ...options, headers: { authorization: `Bearer ${token}`, 'content-type': 'application/json', ...(options.headers || {}) } }); if (!response.ok) { const body = await response.json().catch(() => null); throw new Error(body?.message || '请求失败'); } return response.json(); }
async function load(next = view.value) { loading.value = true; error.value = ''; try { if (next === 'overview') overview.value = await request('overview'); if (next === 'tenants') tenants.value = (await request('tenants')).items; if (next === 'providers') providers.value = await request('providers'); if (next === 'calls') calls.value = (await request('provider-calls')).items; if (next === 'audits') audits.value = (await request('audits')).items; } catch (e) { error.value = e instanceof Error ? e.message : '加载失败'; } finally { loading.value = false; } }
function select(next: View) { view.value = next; load(next); }
async function createTenant() { await request('tenants', { method: 'POST', body: JSON.stringify(form.value) }); dialog.value = null; await load('tenants'); }
async function quota() { await request(`tenants/${form.value.id}/quota`, { method: 'PATCH', body: JSON.stringify({ delta: Number(form.value.delta), reason: form.value.reason }) }); dialog.value = null; await load('tenants'); }
async function createActivation(item: any) { const result = await request(`tenants/${item.id}/activation-codes`, { method: 'POST' }); form.value = { tenant: item.name, code: result.code }; dialog.value = 'activation'; await load('tenants'); }
async function updateProvider(item: any) { await request(`providers/${item.code}`, { method: 'PATCH', body: JSON.stringify({ status: item.status, priority: item.priority, baseUrl: item.baseUrl }) }); await load('providers'); }
const title = computed(() => menu.find(([key]) => key === view.value)?.[1]); onMounted(load);
</script>

<template>
  <div class="admin-shell"><aside class="admin-side"><div class="admin-logo"><span class="admin-logo-mark">✦</span>包小印总控台</div><nav class="admin-menu"><a v-for="item in menu" :key="item[0]" :class="{ 'router-link-active': view === item[0] }" @click="select(item[0])"><b>{{ item[2] }}</b>{{ item[1] }}</a></nav></aside>
    <main class="admin-main"><header class="admin-top"><div><h1 class="admin-title">{{ title }}</h1><p class="admin-subtitle">平台额度、租户授权与 Provider 调用治理</p></div><span class="admin-account">{{ profile.account || '平台管理员' }}</span></header><p v-if="error" style="color:#bb3e5a">{{ error }}</p><div v-if="loading" class="empty">正在读取数据…</div>
      <template v-else-if="view === 'overview' && overview"><section class="stats"><article class="stat"><span class="stat-label">全站用户</span><b class="stat-value">{{ overview.metrics.users }}</b><span class="stat-detail">新增 {{ overview.metrics.newUsers }}</span></article><article class="stat"><span class="stat-label">今日解析</span><b class="stat-value">{{ overview.metrics.todayResolves }}</b><span class="stat-detail">成功率 {{ overview.metrics.successRate == null ? '—' : `${(overview.metrics.successRate * 100).toFixed(1)}%` }}</span></article><article class="stat"><span class="stat-label">Provider 调用</span><b class="stat-value">{{ overview.metrics.providerCalls }}</b><span class="stat-detail">平均 {{ overview.metrics.averageLatencyMs }}ms</span></article><article class="stat"><span class="stat-label">预估成本</span><b class="stat-value">¥{{ overview.metrics.cost }}</b><span class="stat-detail">真实调用汇总</span></article></section></template>
      <template v-else-if="view === 'tenants'"><div class="toolbar"><el-button type="primary" @click="form = { quotaTotal: 1000, capabilities: ['doubao', 'douyin', 'xhs'], adminAccount: '', adminPassword: '', publicCode: '' }; dialog = 'tenant'">创建租户</el-button></div><section class="panel"><table class="table"><thead><tr><th>租户</th><th>小程序租户码</th><th>额度</th><th>微信配置</th><th>服务授权</th><th>用户</th><th></th></tr></thead><tbody><tr v-for="item in tenants" :key="item.id"><td><b>{{ item.name }}</b><br><small>{{ item.status }}</small></td><td>{{ item.publicCode }}</td><td>{{ item.quotaRemaining }} / {{ item.quotaTotal }}</td><td><span class="badge" :class="{ success: item.wechatConfigured }">{{ item.wechatConfigured ? '已配置' : '未配置' }}</span></td><td><span class="badge" :class="{ success: item.serviceActivated }">{{ item.serviceActivated ? '已开通' : '待开通' }}</span></td><td>{{ item._count.users }}</td><td><el-button link type="primary" @click="form = { id: item.id, delta: 100, reason: '' }; dialog = 'quota'">调额度</el-button><el-button link type="primary" @click="createActivation(item)">生成授权码</el-button></td></tr></tbody></table><div v-if="!tenants.length" class="empty">暂无租户</div></section></template>
      <template v-else-if="view === 'providers'"><section class="panel"><table class="table"><thead><tr><th>Provider</th><th>状态</th><th>优先级</th><th>Base URL</th><th>Secret</th><th></th></tr></thead><tbody><tr v-for="item in providers" :key="item.code"><td>{{ item.name }}</td><td><el-select v-model="item.status" style="width:105px"><el-option label="启用" value="ENABLED"/><el-option label="停用" value="DISABLED"/></el-select></td><td><el-input-number v-model="item.priority" :min="1"/></td><td>{{ item.baseUrl }}</td><td>{{ item.secret.last4 || '未配置' }}</td><td><el-button link type="primary" @click="updateProvider(item)">保存</el-button></td></tr></tbody></table></section></template>
      <template v-else-if="view === 'calls'"><section class="panel"><table class="table"><thead><tr><th>Provider</th><th>租户</th><th>平台</th><th>状态</th><th>耗时</th><th>成本</th><th>时间</th></tr></thead><tbody><tr v-for="item in calls" :key="item.id"><td>{{ item.provider.name }}</td><td>{{ item.tenantId }}</td><td>{{ item.platform }}</td><td>{{ item.status }}</td><td>{{ item.latencyMs }}ms</td><td>{{ item.costEstimate }}</td><td>{{ item.createdAt }}</td></tr></tbody></table><div v-if="!calls.length" class="empty">暂无 Provider 调用记录</div></section></template>
      <template v-else-if="view === 'audits'"><section class="panel"><table class="table"><thead><tr><th>动作</th><th>目标</th><th>操作者</th><th>时间</th></tr></thead><tbody><tr v-for="item in audits" :key="item.id"><td>{{ item.action }}</td><td>{{ item.targetType }} · {{ item.targetId || '—' }}</td><td>{{ item.actorId }}</td><td>{{ item.createdAt }}</td></tr></tbody></table><div v-if="!audits.length" class="empty">暂无审计记录</div></section></template>
      <el-dialog :model-value="dialog === 'tenant'" title="创建租户" @update:model-value="dialog = null"><el-form label-position="top"><el-form-item label="租户名称"><el-input v-model="form.name"/></el-form-item><el-form-item label="小程序租户码"><el-input v-model="form.publicCode" placeholder="例如 baoxiaoyin；不填则自动生成"/></el-form-item><el-form-item label="总解析额度"><el-input-number v-model="form.quotaTotal" :min="0"/></el-form-item><el-form-item label="管理员账号"><el-input v-model="form.adminAccount"/></el-form-item><el-form-item label="管理员密码"><el-input v-model="form.adminPassword" type="password"/></el-form-item></el-form><template #footer><el-button @click="dialog = null">取消</el-button><el-button type="primary" @click="createTenant">创建</el-button></template></el-dialog>
      <el-dialog :model-value="dialog === 'quota'" title="调整租户总额度" @update:model-value="dialog = null"><p style="color:#786f84;margin-top:0">用户兑换次数不能突破平台给该租户的总调用额度。</p><el-input-number v-model="form.delta"/><el-input v-model="form.reason" placeholder="调整原因" style="margin-top:14px"/><template #footer><el-button @click="dialog = null">取消</el-button><el-button type="primary" @click="quota">确认</el-button></template></el-dialog>
      <el-dialog :model-value="dialog === 'activation'" title="租户服务授权码" @update:model-value="dialog = null"><p>请将此码交给「{{ form.tenant }}」的租户管理员。它只显示这一次，请立即复制保存。</p><el-input :model-value="form.code" readonly/><template #footer><el-button type="primary" @click="dialog = null">我已保存</el-button></template></el-dialog>
    </main></div>
</template>
