<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
type View = 'overview'|'users'|'ledger'|'codes'|'records'|'quota'|'settings';
function acceptLoginHandoff() { const params = new URLSearchParams(location.search); const handoffToken = params.get('adminToken'); const handoffProfile = params.get('adminProfile'); if (!handoffToken) return; localStorage.setItem('admin-token', handoffToken); if (handoffProfile) localStorage.setItem('admin-profile', handoffProfile); params.delete('adminToken'); params.delete('adminProfile'); history.replaceState({}, document.title, `${location.pathname}${params.size ? `?${params}` : ''}`); }
acceptLoginHandoff();
const api = import.meta.env.VITE_API_BASE_URL || 'http://127.0.0.1:3000'; const profile = JSON.parse(localStorage.getItem('admin-profile') || '{}'); const token = localStorage.getItem('admin-token'); const view = ref<View>('overview'); const loading = ref(false); const error = ref(''); const overview = ref<any>(null); const users = ref<any[]>([]); const ledger = ref<any[]>([]); const codes = ref<any[]>([]); const jobs = ref<any[]>([]); const quota = ref<any>(null); const settings = ref<any>(null); const activationCode = ref(''); const page = ref(1); const search = ref(''); const dialog = ref<'points'|'codes'|null>(null); const form = ref<any>({});
const menu: [View,string,string][]=[['overview','概览','◈'],['users','用户','◎'],['ledger','点数流水','↗'],['codes','兑换码','⌁'],['records','解析记录','▤'],['quota','额度与能力','◌'],['settings','设置','⚙']];
async function request(path:string, options:RequestInit={}) { if(!token) { location.href=import.meta.env.VITE_ADMIN_PORTAL_URL || (location.hostname === 'localhost' ? 'http://localhost:5174/' : `${location.origin}/admin/`); throw new Error('登录已过期'); } const response=await fetch(`${api}/api/tenant-admin/${path}`,{...options,headers:{authorization:`Bearer ${token}`,'content-type':'application/json',...(options.headers||{})}}); if(!response.ok) { const body=await response.json().catch(()=>null); throw new Error(body?.message||'请求失败'); } return response.json(); }
async function load(next=view.value) { loading.value=true;error.value='';try { if(next==='overview')overview.value=await request('overview'); if(next==='users')users.value=(await request(`users?page=${page.value}&q=${encodeURIComponent(search.value)}`)).items; if(next==='ledger')ledger.value=(await request('points-ledger')).items; if(next==='codes')codes.value=(await request('redeem-codes')).items; if(next==='records')jobs.value=(await request('resolve-jobs')).items; if(next==='quota')quota.value=await request('quota-capabilities'); if(next==='settings')settings.value=await request('settings'); }catch(e){error.value=e instanceof Error?e.message:'加载失败';}finally{loading.value=false;} }
function select(next:View){view.value=next;load(next)}
async function submitPoints(){await request(`users/${form.value.id}/points`,{method:'PATCH',body:JSON.stringify({delta:Number(form.value.delta),reason:form.value.reason})});dialog.value=null;await load('users');}
async function submitCodes(){await request('redeem-codes',{method:'POST',body:JSON.stringify({points:Number(form.value.points),count:Number(form.value.count||1)})});dialog.value=null;await load('codes');}
async function saveSettings(){await request('settings',{method:'PATCH',body:JSON.stringify(settings.value)});await load('settings')}
async function activateService(){if(!activationCode.value.trim())return;await request('settings/activate',{method:'POST',body:JSON.stringify({code:activationCode.value})});activationCode.value='';await load('settings');}
const title=computed(()=>menu.find(([key])=>key===view.value)?.[1]||''); onMounted(()=>load());
</script>
<template><div class="admin-shell"><aside class="admin-side"><div class="admin-logo"><span class="admin-logo-mark">✦</span>包小印运营台</div><nav class="admin-menu"><a v-for="item in menu" :key="item[0]" :class="{ 'router-link-active': view===item[0] }" @click="select(item[0])"><b>{{ item[2] }}</b>{{ item[1] }}</a></nav></aside><main class="admin-main"><header class="admin-top"><div><h1 class="admin-title">{{ title }}</h1><p class="admin-subtitle">基于真实租户数据 · 所有敏感操作均留痕</p></div><span class="admin-account">{{ profile.account || '租户管理员' }}</span></header><p v-if="error" style="color:#bb3e5a">{{ error }}</p><div v-if="loading" class="empty">正在读取数据…</div>
<template v-else-if="view==='overview'&&overview"><section class="stats"><article class="stat"><span class="stat-label">今日解析</span><b class="stat-value">{{ overview.metrics.todayResolves }}</b><span class="stat-detail">成功率 {{ overview.metrics.successRate == null ? '—' : `${(overview.metrics.successRate*100).toFixed(1)}%` }}</span></article><article class="stat"><span class="stat-label">用户数</span><b class="stat-value">{{ overview.metrics.users }}</b><span class="stat-detail">今日新增 {{ overview.metrics.newUsers }}</span></article><article class="stat"><span class="stat-label">剩余额度</span><b class="stat-value">{{ overview.tenant.quotaRemaining }}</b><span class="stat-detail">总额度 {{ overview.tenant.quotaTotal }}</span></article><article class="stat"><span class="stat-label">用户点数</span><b class="stat-value">{{ overview.metrics.pointsTotal }}</b><span class="stat-detail">当日兑换 {{ overview.metrics.todayRedemptions }}</span></article></section><section class="grid"><article class="panel"><h2 class="panel-title">今日平台分布</h2><div v-if="overview.platformDistribution.length" class="table"><div v-for="row in overview.platformDistribution" :key="row.platform" style="display:flex;justify-content:space-between;padding:10px 0;border-bottom:1px solid #f0edf4"><span>{{ row.platform }}</span><b>{{ row.count }}</b></div></div><div v-else class="empty">今日暂无成功解析</div></article><article class="panel"><h2 class="panel-title">已授权能力</h2><div style="display:flex;gap:8px;flex-wrap:wrap"><span v-for="cap in overview.capabilities" :key="cap.id" class="badge">{{ cap.capability }}</span></div></article></section></template>
<template v-else-if="view==='users'"><div class="toolbar"><input v-model="search" placeholder="搜索匿名用户标识"><el-button type="primary" @click="load('users')">查询</el-button></div><section class="panel"><table class="table"><thead><tr><th>用户</th><th>点数</th><th>状态</th><th>解析次数</th><th>最近活跃</th><th></th></tr></thead><tbody><tr v-for="user in users" :key="user.id"><td>{{user.openid}}</td><td>{{user.pointsBalance}}</td><td><span class="badge">{{user.status}}</span></td><td>{{user.resolves}}</td><td>{{user.lastActiveAt||'—'}}</td><td><el-button link type="primary" @click="form={id:user.id,delta:1,reason:''};dialog='points'">调点数</el-button></td></tr></tbody></table><div v-if="!users.length" class="empty">暂无用户</div></section></template>
<template v-else-if="view==='ledger'"><section class="panel"><table class="table"><thead><tr><th>用户</th><th>变动</th><th>原因</th><th>时间</th></tr></thead><tbody><tr v-for="item in ledger" :key="item.id"><td>{{item.user}}</td><td :style="{color:item.delta>0?'#238255':'#c34862'}">{{item.delta>0?'+':''}}{{item.delta}}</td><td>{{item.reason}}</td><td>{{item.createdAt}}</td></tr></tbody></table><div v-if="!ledger.length" class="empty">暂无流水</div></section></template>
<template v-else-if="view==='codes'"><div class="toolbar"><el-button type="primary" @click="form={points:10,count:1};dialog='codes'">创建兑换码</el-button></div><section class="panel"><table class="table"><thead><tr><th>提示</th><th>次数</th><th>状态</th><th>兑换用户</th><th>兑换时间</th><th>创建时间</th></tr></thead><tbody><tr v-for="item in codes" :key="item.id"><td>{{item.codeHint}}</td><td>{{item.points}}</td><td><span class="badge">{{item.status}}</span></td><td>{{item.redeemedBy||'—'}}</td><td>{{item.redeemedAt||'—'}}</td><td>{{item.createdAt}}</td></tr></tbody></table><div v-if="!codes.length" class="empty">暂无兑换码</div></section></template>
<template v-else-if="view==='records'"><section class="panel"><table class="table"><thead><tr><th>平台</th><th>用户</th><th>类型</th><th>状态</th><th>Provider</th><th>耗时</th><th>时间</th></tr></thead><tbody><tr v-for="item in jobs" :key="item.id"><td>{{item.platform}}</td><td>{{item.user}}</td><td>{{item.mediaType||'—'}}</td><td><span class="badge" :class="{success:item.status==='SUCCESS'}">{{item.status}}</span></td><td>{{item.provider||'—'}}</td><td>{{item.latencyMs||'—'}} ms</td><td>{{item.createdAt}}</td></tr></tbody></table><div v-if="!jobs.length" class="empty">暂无解析记录</div></section></template>
<template v-else-if="view==='quota'&&quota"><section class="stats"><article class="stat"><span class="stat-label">总额度</span><b class="stat-value">{{quota.tenant.quotaTotal}}</b></article><article class="stat"><span class="stat-label">剩余额度</span><b class="stat-value">{{quota.tenant.quotaRemaining}}</b></article></section><section class="panel" style="margin-top:17px"><h2 class="panel-title">平台能力</h2><table class="table"><tbody><tr v-for="cap in quota.capabilities" :key="cap.id"><td>{{cap.capability}}</td><td><el-switch :model-value="cap.enabled" @change="async (enabled:boolean)=>{await request(`capabilities/${cap.capability}`,{method:'PATCH',body:JSON.stringify({enabled})});load('quota')}"/></td></tr></tbody></table></section></template>
<template v-else-if="view==='settings'&&settings"><section class="panel" style="max-width:760px"><h2 class="panel-title">租户设置</h2><el-form label-position="top"><el-form-item label="小程序名称"><el-input v-model="settings.miniappName"/></el-form-item><el-form-item label="公告"><el-input v-model="settings.notice" type="textarea"/></el-form-item><el-form-item label="新用户初始点数"><el-input-number v-model="settings.initialPoints"/></el-form-item><el-form-item label="单次解析点数"><el-input-number v-model="settings.pointCost" :min="1"/></el-form-item><el-divider>微信小程序配置</el-divider><el-alert :type="settings.wechat?.appid&&settings.wechat?.appsecretConfigured?'success':'warning'" :closable="false" :title="settings.wechat?.appid&&settings.wechat?.appsecretConfigured?'微信登录凭证已配置':'需同时填写 AppID 与 AppSecret，才能启用真实微信登录'" style="margin-bottom:16px"/><el-form-item label="微信 AppID"><el-input v-model="settings.appid" placeholder="例如 wx..."/></el-form-item><el-form-item label="微信 AppSecret"><el-input v-model="settings.appsecret" type="password" show-password placeholder="已配置时留空即可；修改时重新输入完整值"/></el-form-item><el-button type="primary" @click="saveSettings">保存设置</el-button><el-divider>服务开通</el-divider><el-alert :type="settings.service?.activated?'success':'warning'" :closable="false" :title="settings.service?.activated?'服务已开通，可使用去水印解析':'服务尚未开通，请向平台方索取租户服务授权码'" style="margin-bottom:16px"/><div v-if="!settings.service?.activated" class="toolbar"><el-input v-model="activationCode" placeholder="输入平台发放的服务授权码"/><el-button type="primary" @click="activateService">开通服务</el-button></div></el-form></section></template>
<el-dialog :model-value="dialog==='points'" title="调整用户点数" @update:model-value="dialog=null"><el-input-number v-model="form.delta"/><el-input v-model="form.reason" placeholder="填写调整原因" style="margin-top:14px"/><template #footer><el-button @click="dialog=null">取消</el-button><el-button type="primary" @click="submitPoints">确认调整</el-button></template></el-dialog><el-dialog :model-value="dialog==='codes'" title="创建兑换码" @update:model-value="dialog=null"><el-form label-position="top"><el-form-item label="每个兑换码点数"><el-input-number v-model="form.points" :min="1"/></el-form-item><el-form-item label="生成数量"><el-input-number v-model="form.count" :min="1" :max="100"/></el-form-item></el-form><template #footer><el-button @click="dialog=null">取消</el-button><el-button type="primary" @click="submitCodes">创建</el-button></template></el-dialog></main></div></template>
